export const POLICY_ID = "hipaa-safe-harbor-text-v1-browser-experimental";
export const MAX_TEXT_LENGTH = 500_000;

export const PLACEHOLDER_LABELS = Object.freeze({
  PERSON: "PERSON",
  LOCATION: "LOCATION",
  ADDRESS: "ADDRESS",
  ZIP_CODE: "ZIP_CODE",
  DATE: "DATE",
  AGE_OVER_89: "AGE_OVER_89",
  PHONE_NUMBER: "PHONE_NUMBER",
  FAX_NUMBER: "FAX_NUMBER",
  EMAIL_ADDRESS: "EMAIL_ADDRESS",
  US_SSN: "US_SSN",
  MEDICAL_RECORD_NUMBER: "MEDICAL_RECORD_NUMBER",
  HEALTH_PLAN_ID: "HEALTH_PLAN_ID",
  ACCOUNT_NUMBER: "ACCOUNT_NUMBER",
  LICENSE_NUMBER: "LICENSE_NUMBER",
  VEHICLE_ID: "VEHICLE_ID",
  DEVICE_ID: "DEVICE_ID",
  URL: "URL",
  IP_ADDRESS: "IP_ADDRESS",
  BIOMETRIC_ID: "BIOMETRIC_ID",
  UNIQUE_ID: "UNIQUE_ID",
});

export const MANUAL_ENTITY_TYPES = Object.freeze(Object.keys(PLACEHOLDER_LABELS));

export const ENTITY_PRIORITY = Object.freeze({
  MEDICAL_RECORD_NUMBER: 100,
  HEALTH_PLAN_ID: 99,
  US_SSN: 98,
  ACCOUNT_NUMBER: 97,
  LICENSE_NUMBER: 96,
  VEHICLE_ID: 95,
  DEVICE_ID: 94,
  EMAIL_ADDRESS: 93,
  URL: 92,
  IP_ADDRESS: 91,
  PHONE_NUMBER: 90,
  FAX_NUMBER: 90,
  ADDRESS: 85,
  ZIP_CODE: 84,
  PERSON: 80,
  LOCATION: 79,
  AGE_OVER_89: 75,
  DATE: 70,
  BIOMETRIC_ID: 65,
  UNIQUE_ID: 60,
});

export function normalizeEntityType(entityType) {
  return Object.hasOwn(PLACEHOLDER_LABELS, entityType) ? entityType : "UNIQUE_ID";
}
